spring.application.name=ReminderAlertSystem

spring.datasource.url=jdbc:mysql://localhost:3306/reminder_alert_system
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

server.servlet.session.timeout=8h
spring.devtools.restart.enabled=false